spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/training
    username: admin
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8000
app:
  jwt:
    secret: abcdefghijklmnOPQRSTUVWXYZ